### ISSUE TITLE
Module not found: Error: Package path . is not exported from package

### ISSUE THREAD

**Issue by Athari** [lukeed/fetch-event-stream#2]
When I add this line:
```js
import { events } from 'fetch-event-stream';
```
I receive the following error:
```
ERROR in D:\Docs\Projects\NotAIChat\src\providers.js 6:0-44
Module not found: Error: Package path . is not exported from package D:\Docs\Projects\NotAIChat\node_modules\fetch-event-stream (see exports field in D:\Docs\Projects\NotAIChat\node_modules\fetch-event-stream\package.json)
 @ D:\Docs\Projects\NotAIChat\src\app.svelte 45:0-50 895:20-49 917:26-57 1065:19-48 1093:60-91 1326:20-47 1348:26-54 1470:19-46 1498:58-86 2197:20-51 2204:18-54 3175:19-50 3198:17-53 3364:1-25 3378:18-65 3379:16-60 3495:14-50 3640:45-92 3653:25-72 3684:41-85
 @ D:\Docs\Projects\NotAIChat\src\index.js 1:0-31 3:16-19

webpack 5.91.0 compiled with 1 error in 4967 ms
```
Importing all other packages works, so something is unique to this package. I've checked like 100 StackOverflow questions and all of them seem to imply that something is wrong with the import statement. My expertise in Node is pretty low, so I'm out of ideas how to fix this.

**Comment by lukeed** [comment]
There's always something screwy with Webpack. **Recommendation:** Leave it

There is **only** a `"."` key exported in `package.json`, so Webpack is 100% wrong here. [See live npm files](https://www.npmjs.com/package/fetch-event-stream?activeTab=code)

Without having touched webpack in years (and knowing that they intentionally borked/forked early-days' "exports" resolution mapping), my only suggestion is to make sure [this](https://webpack.js.org/configuration/resolve/#resolveconditionnames) is configured to include `import` or `require`. I personally have no faith in webpack resolving the conditions in the spec-compliant manner, so force it.
